// <auto-generated />
using System;
using BudgetApp.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BudgetApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260614162440_DatabaseSeed2")]
    partial class DatabaseSeed2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BudgetApp.Domain.Entities.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("code");

                    b.Property<byte>("DecimalPlaces")
                        .HasColumnType("smallint")
                        .HasColumnName("decimal_places");

                    b.Property<string>("Symbol")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("symbol");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_currencies_code");

                    b.ToTable("currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "PLN",
                            DecimalPlaces = (byte)2,
                            Symbol = "zł"
                        },
                        new
                        {
                            Id = 2,
                            Code = "EUR",
                            DecimalPlaces = (byte)2,
                            Symbol = "€"
                        },
                        new
                        {
                            Id = 3,
                            Code = "USD",
                            DecimalPlaces = (byte)2,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 4,
                            Code = "GBP",
                            DecimalPlaces = (byte)2,
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 5,
                            Code = "CHF",
                            DecimalPlaces = (byte)2,
                            Symbol = "CHF"
                        },
                        new
                        {
                            Id = 6,
                            Code = "JPY",
                            DecimalPlaces = (byte)0,
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 7,
                            Code = "CNY",
                            DecimalPlaces = (byte)2,
                            Symbol = "¥"
                        },
                        new
                        {
                            Id = 8,
                            Code = "HKD",
                            DecimalPlaces = (byte)2,
                            Symbol = "HK$"
                        },
                        new
                        {
                            Id = 9,
                            Code = "SGD",
                            DecimalPlaces = (byte)2,
                            Symbol = "S$"
                        },
                        new
                        {
                            Id = 10,
                            Code = "AUD",
                            DecimalPlaces = (byte)2,
                            Symbol = "A$"
                        },
                        new
                        {
                            Id = 11,
                            Code = "CAD",
                            DecimalPlaces = (byte)2,
                            Symbol = "C$"
                        },
                        new
                        {
                            Id = 12,
                            Code = "NZD",
                            DecimalPlaces = (byte)2,
                            Symbol = "NZ$"
                        },
                        new
                        {
                            Id = 13,
                            Code = "SEK",
                            DecimalPlaces = (byte)2,
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 14,
                            Code = "NOK",
                            DecimalPlaces = (byte)2,
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 15,
                            Code = "DKK",
                            DecimalPlaces = (byte)2,
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 16,
                            Code = "CZK",
                            DecimalPlaces = (byte)2,
                            Symbol = "Kč"
                        },
                        new
                        {
                            Id = 17,
                            Code = "HUF",
                            DecimalPlaces = (byte)0,
                            Symbol = "Ft"
                        },
                        new
                        {
                            Id = 18,
                            Code = "RON",
                            DecimalPlaces = (byte)2,
                            Symbol = "lei"
                        },
                        new
                        {
                            Id = 19,
                            Code = "BGN",
                            DecimalPlaces = (byte)2,
                            Symbol = "лв"
                        },
                        new
                        {
                            Id = 20,
                            Code = "TRY",
                            DecimalPlaces = (byte)2,
                            Symbol = "₺"
                        },
                        new
                        {
                            Id = 21,
                            Code = "UAH",
                            DecimalPlaces = (byte)2,
                            Symbol = "₴"
                        },
                        new
                        {
                            Id = 22,
                            Code = "RUB",
                            DecimalPlaces = (byte)2,
                            Symbol = "₽"
                        },
                        new
                        {
                            Id = 23,
                            Code = "INR",
                            DecimalPlaces = (byte)2,
                            Symbol = "₹"
                        },
                        new
                        {
                            Id = 24,
                            Code = "BRL",
                            DecimalPlaces = (byte)2,
                            Symbol = "R$"
                        },
                        new
                        {
                            Id = 25,
                            Code = "MXN",
                            DecimalPlaces = (byte)2,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 26,
                            Code = "ARS",
                            DecimalPlaces = (byte)2,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 27,
                            Code = "CLP",
                            DecimalPlaces = (byte)0,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 28,
                            Code = "COP",
                            DecimalPlaces = (byte)2,
                            Symbol = "$"
                        },
                        new
                        {
                            Id = 29,
                            Code = "UYU",
                            DecimalPlaces = (byte)2,
                            Symbol = "$U"
                        },
                        new
                        {
                            Id = 30,
                            Code = "ZAR",
                            DecimalPlaces = (byte)2,
                            Symbol = "R"
                        },
                        new
                        {
                            Id = 31,
                            Code = "ILS",
                            DecimalPlaces = (byte)2,
                            Symbol = "₪"
                        },
                        new
                        {
                            Id = 32,
                            Code = "AED",
                            DecimalPlaces = (byte)2,
                            Symbol = "د.إ"
                        },
                        new
                        {
                            Id = 33,
                            Code = "SAR",
                            DecimalPlaces = (byte)2,
                            Symbol = "﷼"
                        },
                        new
                        {
                            Id = 34,
                            Code = "QAR",
                            DecimalPlaces = (byte)2,
                            Symbol = "ر.ق"
                        },
                        new
                        {
                            Id = 35,
                            Code = "KWD",
                            DecimalPlaces = (byte)3,
                            Symbol = "د.ك"
                        },
                        new
                        {
                            Id = 36,
                            Code = "BHD",
                            DecimalPlaces = (byte)3,
                            Symbol = ".د.ب"
                        },
                        new
                        {
                            Id = 37,
                            Code = "OMR",
                            DecimalPlaces = (byte)3,
                            Symbol = "ر.ع."
                        },
                        new
                        {
                            Id = 38,
                            Code = "PKR",
                            DecimalPlaces = (byte)2,
                            Symbol = "₨"
                        },
                        new
                        {
                            Id = 39,
                            Code = "BDT",
                            DecimalPlaces = (byte)2,
                            Symbol = "৳"
                        },
                        new
                        {
                            Id = 40,
                            Code = "LKR",
                            DecimalPlaces = (byte)2,
                            Symbol = "₨"
                        },
                        new
                        {
                            Id = 41,
                            Code = "NPR",
                            DecimalPlaces = (byte)2,
                            Symbol = "₨"
                        },
                        new
                        {
                            Id = 42,
                            Code = "THB",
                            DecimalPlaces = (byte)2,
                            Symbol = "฿"
                        },
                        new
                        {
                            Id = 43,
                            Code = "VND",
                            DecimalPlaces = (byte)0,
                            Symbol = "₫"
                        },
                        new
                        {
                            Id = 44,
                            Code = "IDR",
                            DecimalPlaces = (byte)2,
                            Symbol = "Rp"
                        },
                        new
                        {
                            Id = 45,
                            Code = "PHP",
                            DecimalPlaces = (byte)2,
                            Symbol = "₱"
                        },
                        new
                        {
                            Id = 46,
                            Code = "MYR",
                            DecimalPlaces = (byte)2,
                            Symbol = "RM"
                        },
                        new
                        {
                            Id = 47,
                            Code = "KRW",
                            DecimalPlaces = (byte)0,
                            Symbol = "₩"
                        },
                        new
                        {
                            Id = 48,
                            Code = "EGP",
                            DecimalPlaces = (byte)2,
                            Symbol = "£"
                        },
                        new
                        {
                            Id = 49,
                            Code = "NGN",
                            DecimalPlaces = (byte)2,
                            Symbol = "₦"
                        },
                        new
                        {
                            Id = 50,
                            Code = "KES",
                            DecimalPlaces = (byte)2,
                            Symbol = "KSh"
                        },
                        new
                        {
                            Id = 51,
                            Code = "ISK",
                            DecimalPlaces = (byte)0,
                            Symbol = "kr"
                        },
                        new
                        {
                            Id = 52,
                            Code = "HRK",
                            DecimalPlaces = (byte)2,
                            Symbol = "kn"
                        },
                        new
                        {
                            Id = 53,
                            Code = "RSD",
                            DecimalPlaces = (byte)2,
                            Symbol = "дин."
                        });
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<int?>("DestinationWalletId")
                        .HasColumnType("integer")
                        .HasColumnName("destination_wallet_id");

                    b.Property<int?>("SourceWalletId")
                        .HasColumnType("integer")
                        .HasColumnName("source_wallet_id");

                    b.Property<int>("TransactionType")
                        .HasColumnType("integer")
                        .HasColumnName("transaction_type");

                    b.HasKey("Id")
                        .HasName("pk_transactions");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_transactions_category_id");

                    b.HasIndex("DestinationWalletId")
                        .HasDatabaseName("ix_transactions_destination_wallet_id");

                    b.HasIndex("SourceWalletId")
                        .HasDatabaseName("ix_transactions_source_wallet_id");

                    b.ToTable("transactions", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.TransactionCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int?>("ParentId")
                        .HasColumnType("integer")
                        .HasColumnName("parent_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_transaction_categories");

                    b.HasIndex("ParentId")
                        .HasDatabaseName("ix_transaction_categories_parent_id");

                    b.ToTable("transaction_categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Dom i wyposażenie",
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            Name = "Kultura i rozrywka",
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            Name = "Opłaty",
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            Name = "Samochód",
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            Name = "Specjalne okazje",
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            Name = "Sport",
                            Type = 0
                        },
                        new
                        {
                            Id = 7,
                            Name = "Transport i noclegi",
                            Type = 0
                        },
                        new
                        {
                            Id = 8,
                            Name = "Usługi cyfrowe",
                            Type = 0
                        },
                        new
                        {
                            Id = 9,
                            Name = "Zdrowie i uroda",
                            Type = 0
                        },
                        new
                        {
                            Id = 10,
                            Name = "Jedzenie i napoje",
                            Type = 0
                        },
                        new
                        {
                            Id = 11,
                            Name = "Praca",
                            Type = 1
                        },
                        new
                        {
                            Id = 12,
                            Name = "Inwestycje",
                            Type = 1
                        },
                        new
                        {
                            Id = 13,
                            Name = "Inne",
                            Type = 1
                        },
                        new
                        {
                            Id = 14,
                            Name = "AGD",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 15,
                            Name = "Akcesoria i dekoracje",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 16,
                            Name = "Artykuły papiernicze",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 17,
                            Name = "Elektronika i RTV",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 18,
                            Name = "Kuchnia",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 19,
                            Name = "Meble",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 20,
                            Name = "Narzędzia i sprzęt",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 21,
                            Name = "Odzież",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 22,
                            Name = "Tekstylia",
                            ParentId = 1,
                            Type = 0
                        },
                        new
                        {
                            Id = 23,
                            Name = "Inne aktywności",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 24,
                            Name = "Filmy i seriale",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 25,
                            Name = "Gry",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 26,
                            Name = "Hobby i kolekcjonerstwo",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 27,
                            Name = "Muzyka",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 28,
                            Name = "Komiksy, książki, prasa",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 29,
                            Name = "Eventy",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 30,
                            Name = "Muzea",
                            ParentId = 2,
                            Type = 0
                        },
                        new
                        {
                            Id = 31,
                            Name = "Mandaty",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 32,
                            Name = "Opłaty bankowe",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 33,
                            Name = "Opłaty drobne",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 34,
                            Name = "Opłaty urzędowe",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 35,
                            Name = "Podatki",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 36,
                            Name = "Telefon",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 37,
                            Name = "Usługi pocztowe",
                            ParentId = 3,
                            Type = 0
                        },
                        new
                        {
                            Id = 38,
                            Name = "Akcesoria",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 39,
                            Name = "Mechanik",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 40,
                            Name = "Myjnie i czyszczenie",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 41,
                            Name = "Paliwo",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 42,
                            Name = "Parkingi",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 43,
                            Name = "Ubezpieczenie",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 44,
                            Name = "Przegląd",
                            ParentId = 4,
                            Type = 0
                        },
                        new
                        {
                            Id = 45,
                            Name = "Akcje charytatywne",
                            ParentId = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 46,
                            Name = "Prezenty",
                            ParentId = 5,
                            Type = 0
                        },
                        new
                        {
                            Id = 47,
                            Name = "Odzież i akcesoria",
                            ParentId = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 48,
                            Name = "Sulementy i żywienie",
                            ParentId = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 49,
                            Name = "Zawody",
                            ParentId = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 50,
                            Name = "Rekreacja",
                            ParentId = 6,
                            Type = 0
                        },
                        new
                        {
                            Id = 51,
                            Name = "Koleje",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 52,
                            Name = "Komunikacja miejska",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 53,
                            Name = "Noclegi",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 54,
                            Name = "Samolot",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 55,
                            Name = "Taxi",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 56,
                            Name = "Ubezpieczenia podróżne",
                            ParentId = 7,
                            Type = 0
                        },
                        new
                        {
                            Id = 57,
                            Name = "Kursy i szkolenia",
                            ParentId = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 58,
                            Name = "Narzędzia",
                            ParentId = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 59,
                            Name = "Inne platformy",
                            ParentId = 8,
                            Type = 0
                        },
                        new
                        {
                            Id = 60,
                            Name = "Badania",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 61,
                            Name = "Dentysta",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 62,
                            Name = "Fizjoterapia",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 63,
                            Name = "Fryzjer",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 64,
                            Name = "Lekarstwa i wyroby medyczne",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 65,
                            Name = "Zdrowie intymne",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 66,
                            Name = "Kosmetyki",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 67,
                            Name = "Wizyty u lekarzy",
                            ParentId = 9,
                            Type = 0
                        },
                        new
                        {
                            Id = 68,
                            Name = "Jedzenie poza domem",
                            ParentId = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 69,
                            Name = "Zakupy spożywcze",
                            ParentId = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 70,
                            Name = "Inne",
                            ParentId = 10,
                            Type = 0
                        },
                        new
                        {
                            Id = 71,
                            Name = "Akcje",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 72,
                            Name = "Dywidendy",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 73,
                            Name = "Inne odsetki",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 74,
                            Name = "Lokaty",
                            ParentId = 11,
                            Type = 1
                        },
                        new
                        {
                            Id = 75,
                            Name = "Bonusy bankowe",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 76,
                            Name = "Cashbacki",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 77,
                            Name = "Prezenty",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 78,
                            Name = "Usługi",
                            ParentId = 12,
                            Type = 1
                        },
                        new
                        {
                            Id = 79,
                            Name = "Wypłata",
                            ParentId = 13,
                            Type = 1
                        },
                        new
                        {
                            Id = 80,
                            Name = "Premia",
                            Type = 1
                        });
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("created_at");

                    b.Property<int>("CurrencyId")
                        .HasColumnType("integer")
                        .HasColumnName("currency_id");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deactivated_at");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<int>("WalletTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("wallet_type_id");

                    b.HasKey("Id")
                        .HasName("pk_wallets");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_wallets_currency_id");

                    b.HasIndex("WalletTypeId")
                        .HasDatabaseName("ix_wallets_wallet_type_id");

                    b.ToTable("wallets", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.WalletType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_wallet_types");

                    b.ToTable("wallet_types", (string)null);
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("BudgetApp.Domain.Entities.TransactionCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_transaction_categories_category_id");

                    b.HasOne("BudgetApp.Domain.Entities.Wallet", "DestinationWallet")
                        .WithMany()
                        .HasForeignKey("DestinationWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_wallets_destination_wallet_id");

                    b.HasOne("BudgetApp.Domain.Entities.Wallet", "SourceWallet")
                        .WithMany()
                        .HasForeignKey("SourceWalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transactions_wallets_source_wallet_id");

                    b.Navigation("Category");

                    b.Navigation("DestinationWallet");

                    b.Navigation("SourceWallet");
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.TransactionCategory", b =>
                {
                    b.HasOne("BudgetApp.Domain.Entities.TransactionCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_transaction_categories_transaction_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("BudgetApp.Domain.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_currencies_currency_id");

                    b.HasOne("BudgetApp.Domain.Entities.WalletType", "WalletType")
                        .WithMany()
                        .HasForeignKey("WalletTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_wallets_wallet_types_wallet_type_id");

                    b.Navigation("Currency");

                    b.Navigation("WalletType");
                });

            modelBuilder.Entity("BudgetApp.Domain.Entities.TransactionCategory", b =>
                {
                    b.Navigation("Children");
                });
#pragma warning restore 612, 618
        }
    }
}
